# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.15.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.15.0/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/philip/Documents/OSS/midimessage

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/philip/Documents/OSS/midimessage

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.15.0/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.15.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/philip/Documents/OSS/midimessage/CMakeFiles /Users/philip/Documents/OSS/midimessage/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/philip/Documents/OSS/midimessage/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named manufacturerids

# Build rule for target.
manufacturerids: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 manufacturerids
.PHONY : manufacturerids

# fast build rule for target.
manufacturerids/fast:
	$(MAKE) -f CMakeFiles/manufacturerids.dir/build.make CMakeFiles/manufacturerids.dir/build
.PHONY : manufacturerids/fast

#=============================================================================
# Target rules for targets named example-sample

# Build rule for target.
example-sample: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example-sample
.PHONY : example-sample

# fast build rule for target.
example-sample/fast:
	$(MAKE) -f CMakeFiles/example-sample.dir/build.make CMakeFiles/example-sample.dir/build
.PHONY : example-sample/fast

#=============================================================================
# Target rules for targets named midimessage

# Build rule for target.
midimessage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 midimessage
.PHONY : midimessage

# fast build rule for target.
midimessage/fast:
	$(MAKE) -f CMakeFiles/midimessage.dir/build.make CMakeFiles/midimessage.dir/build
.PHONY : midimessage/fast

example/sample.o: example/sample.cpp.o

.PHONY : example/sample.o

# target to build an object file
example/sample.cpp.o:
	$(MAKE) -f CMakeFiles/example-sample.dir/build.make CMakeFiles/example-sample.dir/example/sample.cpp.o
.PHONY : example/sample.cpp.o

example/sample.i: example/sample.cpp.i

.PHONY : example/sample.i

# target to preprocess a source file
example/sample.cpp.i:
	$(MAKE) -f CMakeFiles/example-sample.dir/build.make CMakeFiles/example-sample.dir/example/sample.cpp.i
.PHONY : example/sample.cpp.i

example/sample.s: example/sample.cpp.s

.PHONY : example/sample.s

# target to generate assembly for a file
example/sample.cpp.s:
	$(MAKE) -f CMakeFiles/example-sample.dir/build.make CMakeFiles/example-sample.dir/example/sample.cpp.s
.PHONY : example/sample.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/midimessage.dir/build.make CMakeFiles/midimessage.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/midimessage.dir/build.make CMakeFiles/midimessage.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/midimessage.dir/build.make CMakeFiles/midimessage.dir/main.cpp.s
.PHONY : main.cpp.s

src/midimessage.o: src/midimessage.cpp.o

.PHONY : src/midimessage.o

# target to build an object file
src/midimessage.cpp.o:
	$(MAKE) -f CMakeFiles/midimessage.dir/build.make CMakeFiles/midimessage.dir/src/midimessage.cpp.o
.PHONY : src/midimessage.cpp.o

src/midimessage.i: src/midimessage.cpp.i

.PHONY : src/midimessage.i

# target to preprocess a source file
src/midimessage.cpp.i:
	$(MAKE) -f CMakeFiles/midimessage.dir/build.make CMakeFiles/midimessage.dir/src/midimessage.cpp.i
.PHONY : src/midimessage.cpp.i

src/midimessage.s: src/midimessage.cpp.s

.PHONY : src/midimessage.s

# target to generate assembly for a file
src/midimessage.cpp.s:
	$(MAKE) -f CMakeFiles/midimessage.dir/build.make CMakeFiles/midimessage.dir/src/midimessage.cpp.s
.PHONY : src/midimessage.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... manufacturerids"
	@echo "... example-sample"
	@echo "... midimessage"
	@echo "... example/sample.o"
	@echo "... example/sample.i"
	@echo "... example/sample.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/midimessage.o"
	@echo "... src/midimessage.i"
	@echo "... src/midimessage.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

